services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  api:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
      - rabbitmq
      - mongo
    environment:
      - ConnectionStrings__SqlServer=Server=sqlserver;Database=OrdersDb;User Id=sa;Password=Your_password123;
      - MongoDb__ConnectionString=mongodb://mongo:27017
      - MongoDb__DatabaseName=orders